version: '3'
services:
    jenkins:
        container_name: jenkins-master-dev
        image: jenkins-master-dev:v1
        build:
            context: Jenkins
        ports:
            - "8081:8080"
            - "50001:50000"
        volumes:
            - "jenkins-dev:/var/jenkins_home"
        networks:
            - jenkins-dev
networks:
  jenkins-dev:
volumes:
  jenkins-dev: